version: 1.0.{build}

image: Visual Studio 2022

environment:
  matrix:
    - nodejs_version: "20"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - powershell -c "irm bun.sh/install.ps1 | iex"
  - set PATH=%USERPROFILE%\.bun\bin;%PATH%
  - bun --version
  - bun install

build: off

test_script:
  - bun run build
  - bun test

# Enable Remote Desktop Protocol (RDP) on build failure for mid-execution debugging
# on_failure:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
